name: "Update PR Comment"
description: "Create or update a PR comment using the first line as an identifier"
author: "JD Boivin"

inputs:
  token:
    description: "GitHub token for authentication"
    required: false
    default: ${{ github.token }}
  issue-number:
    description: "Pull request or issue number (defaults to current PR number)"
    required: false
    default: ""
  body:
    description: "Comment body. The first line is used to identify the comment for updates."
    required: false
  template-pr-cleanup:
    description: "Use PR cleanup template"
    required: false
    default: "false"
  template-pr-deploy:
    description: "Use PR deploy template"
    required: false
    default: "false"
  template-repository-name:
    description: "Repository name for template (e.g., github.event.repository.name)"
    required: false
    default: ${{ github.event.repository.name }}
  template-sha:
    description: "Commit SHA for template (e.g., github.sha)"
    required: false
    default: ${{ github.sha }}
  template-status:
    description: "Status for template: 'success', 'progress', or 'fail'"
    required: false
    default: ""
  template-version:
    description: "Version for template"
    required: false
    default: ""
  template-future-version:
    description: "Future version for template"
    required: false
    default: ""
  template-environment:
    description: "Environment for template"
    required: false
    default: ""
  template-url:
    description: "URL for template"
    required: false
    default: ""
  template-pattern:
    description: "Pattern for cleanup template"
    required: false
    default: ""
  template-versions-markdown:
    description: "Versions markdown for cleanup template"
    required: false
    default: ""
  template-logs-url:
    description: "Logs URL for template"
    required: false
    default: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  update-linked-issue:
    description: "Whether to also update linked issue comments (default: true)"
    required: false
    default: 'true'

outputs:
  comment-id:
    description: "The ID of the created or updated comment"
    value: ${{ steps.update-comment.outputs.comment-id }}
  comment-url:
    description: "The URL of the created or updated comment"
    value: ${{ steps.update-comment.outputs.comment-url }}
  comment-body:
    description: "The body of the created or updated comment"
    value: ${{ steps.update-comment.outputs.comment-body }}

runs:
  using: "composite"
  steps:
    - name: Update Comment
      id: update-comment
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        ISSUE_NUMBER_INPUT: ${{ inputs.issue-number }}
        COMMENT_BODY: ${{ inputs.body }}
        TEMPLATE_PR_CLEANUP: ${{ inputs.template-pr-cleanup }}
        TEMPLATE_PR_DEPLOY: ${{ inputs.template-pr-deploy }}
        TEMPLATE_REPOSITORY_NAME: ${{ inputs.template-repository-name }}
        TEMPLATE_SHA: ${{ inputs.template-sha }}
        TEMPLATE_STATUS: ${{ inputs.template-status }}
        TEMPLATE_VERSION: ${{ inputs.template-version }}
        TEMPLATE_FUTURE_VERSION: ${{ inputs.template-future-version }}
        TEMPLATE_ENVIRONMENT: ${{ inputs.template-environment }}
        TEMPLATE_URL: ${{ inputs.template-url }}
        TEMPLATE_PATTERN: ${{ inputs.template-pattern }}
        TEMPLATE_VERSIONS_MARKDOWN: ${{ inputs.template-versions-markdown }}
        TEMPLATE_LOGS_URL: ${{ inputs.template-logs-url }}
      run: |
        # Use provided issue number or default to PR number
        if [ -z "$ISSUE_NUMBER_INPUT" ]; then
          ISSUE_NUMBER="${{ github.event.pull_request.number }}"
          echo "Using default PR number: $ISSUE_NUMBER"
        else
          ISSUE_NUMBER="$ISSUE_NUMBER_INPUT"
          echo "Using provided issue number: $ISSUE_NUMBER"
        fi

        # Map status to display text
        case "$TEMPLATE_STATUS" in
          "success")
            STATUS_DISPLAY="✅ Deploy successful!"
            ;;
          "progress")
            STATUS_DISPLAY="🟡 Deploy in progress..."
            ;;
          "fail")
            STATUS_DISPLAY="❌ Deploy failed"
            ;;
          *)
            STATUS_DISPLAY="$TEMPLATE_STATUS"
            ;;
        esac

        # Generate body from template if requested
        if [ "$TEMPLATE_PR_CLEANUP" = "true" ]; then
          echo "Using PR cleanup template"
          COMMENT_BODY="## Deploying ${TEMPLATE_REPOSITORY_NAME} 🚀

        | Status | 🧹 **Cleaned up** |
        |:-------|:------------------|
        | **Environment** | \`${TEMPLATE_ENVIRONMENT}\` |
        | **Pattern** | \`${TEMPLATE_PATTERN}\` |
        | **Version** | \`${TEMPLATE_FUTURE_VERSION}\` |

        **Cleanup completed:**
        - ✓ Git tags deleted
        - ✓ Docker images removed from registry
        - ✓ Helm charts removed from registry
        - ✓ GitHub deployments deleted

        **Versions cleaned:**
        ${TEMPLATE_VERSIONS_MARKDOWN:-_No versions found_}"
        elif [ "$TEMPLATE_PR_DEPLOY" = "true" ]; then
          echo "Using PR deploy template"
          COMMENT_BODY="## Deploying ${TEMPLATE_REPOSITORY_NAME} 🚀

        | Latest commit | ${TEMPLATE_SHA} |
        |:--------------|:----------------|
        | **Status** | ${STATUS_DISPLAY} |
        | **Version** | \`${TEMPLATE_VERSION}\` |
        | **Future Version** | \`${TEMPLATE_FUTURE_VERSION}\` |
        | **Environment** | \`${TEMPLATE_ENVIRONMENT}\` |
        | **URL** | ${TEMPLATE_URL} |

        [View logs](${TEMPLATE_LOGS_URL})"
        elif [ -z "$COMMENT_BODY" ]; then
          echo "Error: Either body or a template must be provided"
          exit 1
        fi

        # Extract first line to use as identifier
        FIRST_LINE=$(echo "$COMMENT_BODY" | head -n 1)
        echo "Searching for comment with identifier: $FIRST_LINE"

        # Search for existing comment containing the first line
        COMMENT_ID=$(gh api \
          repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/comments \
          --jq ".[] | select(.body | startswith(\"$FIRST_LINE\")) | .id" \
          | head -n 1)

        if [ -z "$COMMENT_ID" ]; then
          echo "No existing comment found. Creating new comment..."
          RESPONSE=$(gh api \
            repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/comments \
            -f body="$COMMENT_BODY")
          COMMENT_ID=$(echo "$RESPONSE" | jq -r '.id')
          COMMENT_URL=$(echo "$RESPONSE" | jq -r '.html_url')
          echo "Created comment with ID: $COMMENT_ID"
        else
          echo "Found existing comment with ID: $COMMENT_ID. Updating..."
          RESPONSE=$(gh api \
            --method PATCH \
            repos/${{ github.repository }}/issues/comments/${COMMENT_ID} \
            -f body="$COMMENT_BODY")
          COMMENT_URL=$(echo "$RESPONSE" | jq -r '.html_url')
          echo "Updated comment with ID: $COMMENT_ID"
        fi

        echo "comment-id=$COMMENT_ID" >> $GITHUB_OUTPUT
        echo "comment-url=$COMMENT_URL" >> $GITHUB_OUTPUT
        echo "comment-body<<EOF" >> $GITHUB_OUTPUT
        echo "$COMMENT_BODY" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        echo "Comment URL: $COMMENT_URL"

    - name: Update Linked Issue Comment
      id: update-linked-issue
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        ISSUE_NUMBER_INPUT: ${{ inputs.issue-number }}
        COMMENT_BODY: ${{ steps.update-comment.outputs.comment-body }}
        UPDATE_LINKED_ISSUE: ${{ inputs.update-linked-issue }}
      run: |
        # Check if feature is enabled
        if [ "$UPDATE_LINKED_ISSUE" != "true" ]; then
          echo "Linked issue update is disabled"
          exit 0
        fi

        # Only proceed if we're in a PR context and not explicitly targeting an issue
        if [ -z "${{ github.event.pull_request.number }}" ] || [ -n "$ISSUE_NUMBER_INPUT" ]; then
          echo "Skipping linked issue update: not in PR context or explicit issue number provided"
          exit 0
        fi

        PR_NUMBER="${{ github.event.pull_request.number }}"
        echo "Looking for linked issues in PR #$PR_NUMBER"

        # First, try to get linked issues using GitHub's timeline API
        # This captures issues linked via "closes #X", "fixes #X", etc.
        LINKED_ISSUE=$(gh api \
          repos/${{ github.repository }}/issues/${PR_NUMBER}/timeline \
          --jq '.[] | select(.event == "connected") | .source.issue.number' \
          | head -n 1)

        # If no linked issue found via timeline, parse PR body for #XXX references
        if [ -z "$LINKED_ISSUE" ]; then
          echo "No linked issue found via timeline API, checking PR body..."
          PR_BODY=$(gh api repos/${{ github.repository }}/pulls/${PR_NUMBER} --jq '.body')

          # Extract first issue reference (#XXX) from PR body
          # This regex matches #followed by digits (issue number)
          LINKED_ISSUE=$(echo "$PR_BODY" | grep -oE '#[0-9]+' | head -n 1 | tr -d '#')
        fi

        if [ -z "$LINKED_ISSUE" ]; then
          echo "No linked issue found"
          exit 0
        fi

        echo "Found linked issue: #$LINKED_ISSUE"

        # Verify the linked issue exists and is actually an issue (not a PR)
        ISSUE_TYPE=$(gh api repos/${{ github.repository }}/issues/${LINKED_ISSUE} --jq '.pull_request // empty')

        if [ -n "$ISSUE_TYPE" ]; then
          echo "Linked item #$LINKED_ISSUE is a PR, not an issue. Skipping."
          exit 0
        fi

        echo "Updating comment in linked issue #$LINKED_ISSUE"

        # Extract first line to use as identifier
        FIRST_LINE=$(echo "$COMMENT_BODY" | head -n 1)

        # Search for existing comment in the linked issue
        ISSUE_COMMENT_ID=$(gh api \
          repos/${{ github.repository }}/issues/${LINKED_ISSUE}/comments \
          --jq ".[] | select(.body | startswith(\"$FIRST_LINE\")) | .id" \
          | head -n 1)

        if [ -z "$ISSUE_COMMENT_ID" ]; then
          echo "Creating new comment in linked issue #$LINKED_ISSUE"
          RESPONSE=$(gh api \
            repos/${{ github.repository }}/issues/${LINKED_ISSUE}/comments \
            -f body="$COMMENT_BODY")
          ISSUE_COMMENT_ID=$(echo "$RESPONSE" | jq -r '.id')
          ISSUE_COMMENT_URL=$(echo "$RESPONSE" | jq -r '.html_url')
          echo "Created comment with ID: $ISSUE_COMMENT_ID"
        else
          echo "Updating existing comment in linked issue #$LINKED_ISSUE (ID: $ISSUE_COMMENT_ID)"
          RESPONSE=$(gh api \
            --method PATCH \
            repos/${{ github.repository }}/issues/comments/${ISSUE_COMMENT_ID} \
            -f body="$COMMENT_BODY")
          ISSUE_COMMENT_URL=$(echo "$RESPONSE" | jq -r '.html_url')
          echo "Updated comment with ID: $ISSUE_COMMENT_ID"
        fi

        echo "Linked issue comment URL: $ISSUE_COMMENT_URL"

branding:
  icon: "message-circle"
  color: "blue"
